language: node_js
sudo: false
node_js:
- "8"
- "10"
- "12"
- "13"
env:
  - NPM_SCRIPT=test:browserless
matrix:
  include:
    # Run browser tests only on one Node.js version to save time.
    - node_js: "12"
      env:
        - NPM_SCRIPT="test:browser"
        - BROWSERS="ChromeHeadless,FirefoxHeadless"
      addons:
        chrome: stable
        firefox: latest
    # Run tests against the slim build.
    - node_js: "12"
      env:
        - NPM_SCRIPT="test:slim"
        - BROWSERS="ChromeHeadless"
      addons:
        chrome: stable
    # Run tests against the no-deprecated build.
    - node_js: "12"
      env:
        - NPM_SCRIPT="test:no-deprecated"
        - BROWSERS="ChromeHeadless"
      addons:
        chrome: stable
    # Run ES module tests.
    - node_js: "12"
      env:
        - NPM_SCRIPT="test:esmodules"
        - BROWSERS="ChromeHeadless"
      addons:
        chrome: stable
    # Run AMD tests.
    - node_js: "12"
      env:
        - NPM_SCRIPT="test:amd"
        - BROWSERS="ChromeHeadless"
      addons:
        chrome: stable
    # Run tests on Firefox ESR as well.
    - node_js: "12"
      env:
        - NPM_SCRIPT="test:browser"
        - BROWSERS="FirefoxHeadless"
      addons:
        firefox: latest-esr
script:
  - npm run $NPM_SCRIPT
