name: Browserstack

on:
  push:
    branches:
      - 3.x-stable

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      NODE_VERSION: 22.x
    name: ${{ matrix.BROWSER }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.BROWSER }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        BROWSER:
          - 'IE_11'
          - 'IE_10'
          - 'IE_9'
          - 'Safari_latest'
          - 'Safari_latest-1'
          - 'Chrome_latest'
          - 'Chrome_latest-1'
          - 'Opera_latest'
          - 'Edge_latest'
          - 'Edge_latest-1'
          - 'Edge_18'
          - 'Firefox_latest'
          - 'Firefox_latest-1'
          - 'Firefox_115'
          - 'Firefox_102'
          - 'Firefox_91'
          - 'Firefox_78'
          - 'Firefox_60'
          - 'Firefox_48'
          - '__iOS_18'
          - '__iOS_17'
          - '__iOS_16'
          - '__iOS_15'
          - '__iOS_14'
          - '__iOS_13'
          - '__iOS_12'
          - '__iOS_11'

          # iOS 10 is a tier 4 device as of January 2025 and its availability
          # is poor, leading to frequent test timeouts. Skip testing on it.
          # See https://www.browserstack.com/device-tiers
          # - '__iOS_10'

          # Versions below are not officially supported by BrowserStack as
          # they use emulators instead of real devices. We include them as
          # long as they still work.
          - '__iOS_9'
          - '__iOS_8'
          # iOS 7 emulators no longer work properly
          # - '__iOS_7'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-lock-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-lock-

      - name: Install dependencies
        run: npm install

      - name: Build jQuery
        run: npm run build:all

      - name: Pretest script
        run: npm run pretest

      - name: Run tests
        run: |
          npm run test:unit -- -v -c jtr-isolate.yml \
            --browserstack "${{ matrix.BROWSER }}" \
            --run-id ${{ github.run_id }}
