name: Browserstack

on:
  push:
    branches:
      - 3.x-stable

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      NODE_VERSION: 22.x
    name: ${{ matrix.BROWSER }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.BROWSER }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        BROWSER:
          - 'IE_11'
          - 'IE_10'
          - 'IE_9'
          - 'Safari_latest'
          # JTR doesn't take into account the jump from Safari 18 to 26,
          # so we need to specify versions explicitly.
          # See https://github.com/jquery/jquery-test-runner/issues/17
          - 'Safari_18'
          - 'Chrome_latest'
          - 'Chrome_latest-1'
          - 'Opera_latest'
          - 'Edge_latest'
          - 'Edge_latest-1'
          - 'Edge_18'
          - 'Firefox_latest'
          - 'Firefox_latest-1'
          - 'Firefox_128'
          - 'Firefox_115'
          - 'Firefox_102'
          - 'Firefox_91'
          - 'Firefox_78'
          - 'Firefox_60'
          - 'Firefox_48'

          - '_:iPhone 17_iOS_26'
          - '_:iPhone 16_iOS_18'
          - '_:iPhone 15 Pro_iOS_17'
          - '_:iPhone 14_iOS_16'
          - '_:iPhone 13_iOS_15'
          - '_:iPhone 12_iOS_14'
          - '_:iPhone 11_iOS_13'
          # iOS 12 & older is not officially supported by BrowserStack as
          # it mostly runs on emulators instead of real devices. We include
          # those versions as long as they still work.
          - '_:iPhone XS_iOS_12'
          - '_:iPhone X_iOS_11'
          # iOS 10 real device is in tier 4 as of January 2025 and its
          # availability is poor, leading to frequent test timeouts. Emulators
          # don't work either. Skip testing on this version.
          # See https://www.browserstack.com/device-tiers
          # - '_:iPhone 7_iOS_10'
          - '_:iPhone 6S_iOS_9'
          - '_:iPhone 6_iOS_8'
          # iOS 7 emulators no longer work properly
          # - '_:iPhone 5S_iOS_7'

          - '_:iPad Air 13 2025_iOS_26'
          - '_:iPad Air 13 2025_iOS_18'
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build jQuery
        run: npm run build:all

      - name: Pretest script
        run: npm run pretest

      - name: Run tests
        run: |
          npm run test:unit -- -v -c jtr-isolate.yml \
            --browserstack "${{ matrix.BROWSER }}" \
            --run-id ${{ github.run_id }}
