name: Browserstack (Manual Dispatch)

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module to test'
        required: true
        type: choice
        options:
          - 'basic'
          - 'ajax'
          - 'animation'
          - 'attributes'
          - 'callbacks'
          - 'core'
          - 'css'
          - 'data'
          - 'deferred'
          - 'deprecated'
          - 'dimensions'
          - 'effects'
          - 'event'
          - 'manipulation'
          - 'offset'
          - 'queue'
          - 'selector'
          - 'serialize'
          - 'support'
          - 'traversing'
          - 'tween'
      browser:
        description: 'Browser to test, in form of \"browser_[browserVersion | :device]_os_osVersion\"'
        required: false
        type: string
        default: 'chrome__windows_11'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build jQuery
        run: npm run build:all

      - name: Pretest script
        run: npm run pretest

      - name: Run tests
        run: npm run test:unit -- \
          -v --browserstack ${{ inputs.browser }} \
          -f module=${{ inputs.module }}
