name: Filestash

on:
  push:
    branches:
      - 3.x-stable

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  update:
    name: Update Filestash
    runs-on: ubuntu-latest
    # skip on forks
    if: ${{ github.repository == 'jquery/jquery' }}
    environment: filestash
    env:
      NODE_VERSION: 20.x
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-lock-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-lock-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:all

      - name: Set up SSH
        run: |
          install --directory ~/.ssh --mode 700
          base64 --decode <<< "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 -H "${{ secrets.FILESTASH_SERVER }}" >> ~/.ssh/known_hosts

      - name: Upload to Filestash
        run: |
          rsync dist/jquery.js filestash@"${{ secrets.FILESTASH_SERVER }}":jquery-3.x-git.js
          rsync dist/jquery.min.js filestash@"${{ secrets.FILESTASH_SERVER }}":jquery-3.x-git.min.js
          rsync dist/jquery.min.map filestash@"${{ secrets.FILESTASH_SERVER }}":jquery-3.x-git.min.map

          rsync dist/jquery.slim.js filestash@"${{ secrets.FILESTASH_SERVER }}":jquery-3.x-git.slim.js
          rsync dist/jquery.slim.min.js filestash@"${{ secrets.FILESTASH_SERVER }}":jquery-3.x-git.slim.min.js
          rsync dist/jquery.slim.min.map filestash@"${{ secrets.FILESTASH_SERVER }}":jquery-3.x-git.slim.min.map
