name: Filestash

on:
  push:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  update:
    runs-on: ubuntu-latest
    environment: filestash
    env:
      NODE_VERSION: 20.x
    name: Update Filestash
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:all

      - name: Set up SSH
        run: install --directory ~/.ssh --mode 700
      - name: Add ssh id
        run: base64 --decode <<< "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
      - name: Allow ssh id to be read/write
        run: chmod 600 ~/.ssh/id_ed25519
      - name: Run ssh-keyscan
        run: ssh-keyscan -t ed25519 -H "${{ secrets.FILESTASH_SERVER }}" >> ~/.ssh/known_hosts

      - name: Upload to Filestash
        env: 
          FILESTASH_SERVER: ${{ secrets.FILESTASH_SERVER }}
        run: .github/workflows/scripts/filestash.sh