name: Reproducible Builds
on:
  push:
    # On tags
    tags:
      - '*'
  # Or manually
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to verify (>= 4.0.0-rc.1)'
        required: false


jobs:
  run:
    name: Verify release
    runs-on: ubuntu-latest
    # skip on forks
    if: ${{ github.repository == 'jquery/jquery' }}
    env:
      NODE_VERSION: 22.x
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - run: npm run release:verify
        env:
          VERSION: ${{ github.event.inputs.version || github.ref_name }}
